In [8]:
import pandas as pd

In [9]:
#pandas contain 3 types of data
# Series : - contain 1D data
# dataframe : - contain 2D data
# Depre

In [10]:
# SERIES

s=pd.Series(range(5))
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [11]:
# CREATE SERES USING LIST TUPLE STRING SET AND DIC

In [12]:
li=[1,2,4,5,6,7]
pd.Series(li)

0    1
1    2
2    4
3    5
4    6
5    7
dtype: int64

In [13]:
tu = (1,2,4,5,7,5)
pd.Series(tu)

0    1
1    2
2    4
3    5
4    7
5    5
dtype: int64

In [14]:
# se={1}
# print(type(se))
# pd.Series(se)

In [15]:
s="abcdefg"
pd.Series(s)

0    abcdefg
dtype: object

In [16]:
dc = {1:"a",5:"b",3:"c","dcd":23}
pd.Series(dc)

1       a
5       b
3       c
dcd    23
dtype: object

In [17]:
ind=['a','b','c','d','e']

s=pd.Series(range(5),index=ind,dtype="float32")

In [18]:
s.dtype
# index
# values
# dtype
# ndim
# size
# shape

dtype('float32')

In [19]:
# dataframe

d=pd.DataFrame(
    {"name" : ["Shubham Sangavkar","akash ac","prathamesh patil","Swaraj naik"],
    "age": [20,22,23,29],
    "salary":[100000,21212,222,232]}
    
)
d

                name  age  salary
0  Shubham Sangavkar   20  100000
1           akash ac   22   21212
2   prathamesh patil   23     222
3        Swaraj naik   29     232

In [20]:
d.values , d.shape ,d.shape , d.ndim ,d["name"].dtype

(array([['Shubham Sangavkar', 20, 100000],
        ['akash ac', 22, 21212],
        ['prathamesh patil', 23, 222],
        ['Swaraj naik', 29, 232]], dtype=object),
 (4, 3),
 (4, 3),
 2,
 dtype('O'))

In [21]:
d.to_numpy()

array([['Shubham Sangavkar', 20, 100000],
       ['akash ac', 22, 21212],
       ['prathamesh patil', 23, 222],
       ['Swaraj naik', 29, 232]], dtype=object)

In [22]:
d.to_csv("data.csv",index=False)

In [23]:
d.to_excel("data.xlsx")

In [24]:
d["name"]

0    Shubham Sangavkar
1             akash ac
2     prathamesh patil
3          Swaraj naik
Name: name, dtype: object

In [25]:
d.name

0    Shubham Sangavkar
1             akash ac
2     prathamesh patil
3          Swaraj naik
Name: name, dtype: object

In [26]:
d.loc[:,['name']]
d.loc[:,['name','salary']]

                name  salary
0  Shubham Sangavkar  100000
1           akash ac   21212
2   prathamesh patil     222
3        Swaraj naik     232

In [27]:
d.iloc[2:4,0::2]

               name  salary
2  prathamesh patil     222
3       Swaraj naik     232

In [28]:
d['salary'].max()
d['salary'].min()

np.int64(222)

In [29]:
d.query('salary== salary.max()')

                name  age  salary
0  Shubham Sangavkar   20  100000

In [30]:
d.query('salary>= 5000')

                name  age  salary
0  Shubham Sangavkar   20  100000
1           akash ac   22   21212

In [31]:
d["f_name"] = d['name'].apply(lambda mn:mn.split()[0])
d

                name  age  salary      f_name
0  Shubham Sangavkar   20  100000     Shubham
1           akash ac   22   21212       akash
2   prathamesh patil   23     222  prathamesh
3        Swaraj naik   29     232      Swaraj

In [32]:
d["l_name"]= d["name"].apply(lambda mn: mn.split()[-1])

In [33]:
d

                name  age  salary      f_name     l_name
0  Shubham Sangavkar   20  100000     Shubham  Sangavkar
1           akash ac   22   21212       akash         ac
2   prathamesh patil   23     222  prathamesh      patil
3        Swaraj naik   29     232      Swaraj       naik

In [34]:
d['new_sal'] = d['salary'].apply(lambda sal : sal * .1 + sal)
d

                name  age  salary      f_name     l_name   new_sal
0  Shubham Sangavkar   20  100000     Shubham  Sangavkar  110000.0
1           akash ac   22   21212       akash         ac   23333.2
2   prathamesh patil   23     222  prathamesh      patil     244.2
3        Swaraj naik   29     232      Swaraj       naik     255.2

In [35]:
d['comp'] = "DYP"
d

                name  age  salary      f_name     l_name   new_sal comp
0  Shubham Sangavkar   20  100000     Shubham  Sangavkar  110000.0  DYP
1           akash ac   22   21212       akash         ac   23333.2  DYP
2   prathamesh patil   23     222  prathamesh      patil     244.2  DYP
3        Swaraj naik   29     232      Swaraj       naik     255.2  DYP

In [36]:
d.drop("salary" , axis =1 , inplace = True)
d

                name  age      f_name     l_name   new_sal comp
0  Shubham Sangavkar   20     Shubham  Sangavkar  110000.0  DYP
1           akash ac   22       akash         ac   23333.2  DYP
2   prathamesh patil   23  prathamesh      patil     244.2  DYP
3        Swaraj naik   29      Swaraj       naik     255.2  DYP

In [37]:
d.query("name.str.startswith('S')")

                name  age   f_name     l_name   new_sal comp
0  Shubham Sangavkar   20  Shubham  Sangavkar  110000.0  DYP
3        Swaraj naik   29   Swaraj       naik     255.2  DYP

In [38]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

f = pd.read_csv(path)
f.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

In [39]:
f.shape

(18207, 18)

In [40]:
f.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [41]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [42]:
f.isnull().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [43]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [44]:
f.dropna(inplace=True)

In [45]:
f.isna().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [46]:
f["Preferred Foot"]

0         Left
1        Right
2        Right
3        Right
4        Right
         ...
18202    Right
18203    Right
18204    Right
18205    Right
18206    Right
Name: Preferred Foot, Length: 17907, dtype: object

In [47]:
f.rename(columns={"Preferred Foot":"P_Foot"},inplace=True)
f.head()
f.columns
f.P_Foot

0         Left
1        Right
2        Right
3        Right
4        Right
         ...
18202    Right
18203    Right
18204    Right
18205    Right
18206    Right
Name: P_Foot, Length: 17907, dtype: object

In [48]:
f.columns = f.columns.str.replace(" ","_")
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [49]:
f['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Paris Saint-Germain',
       'Manchester United', 'Manchester City', 'Chelsea', 'Real Madrid',
       'Atlético Madrid', 'FC Bayern München', 'Tottenham Hotspur',
       'Liverpool', 'Napoli', 'Arsenal', 'Milan', 'Inter', 'Lazio',
       'Borussia Dortmund', 'Vissel Kobe', 'Olympique Lyonnais', 'Roma',
       'Valencia CF', 'Guangzhou Evergrande Taobao FC', 'FC Porto',
       'FC Schalke 04', 'Beşiktaş JK', 'LA Galaxy', 'Sporting CP',
       'Real Betis', 'Olympique de Marseille', 'RC Celta',
       'Bayer 04 Leverkusen', 'Real Sociedad', 'Villarreal CF',
       'Sevilla FC', 'SL Benfica', 'AS Saint-Étienne', 'AS Monaco',
       'Leicester City', 'Atalanta', 'Grêmio', 'Atlético Mineiro',
       'RB Leipzig', 'Ajax', 'Dalian YiFang FC', 'Everton',
       'West Ham United', '1. FC Köln', 'TSG 1899 Hoffenheim',
       'Shanghai SIPG FC', 'OGC Nice', 'Al Nassr',
       'Wolverhampton Wanderers', 'Borussia Mönchengladbach',
       'Hertha BSC', 'SV Werder Bremen', 'Cruzeiro',
       'Athletic Club de Bilbao', 'Torino', 'Medipol Başakşehir FK',
       'Beijing Sinobo Guoan FC', 'Crystal Palace', 'PFC CSKA Moscow',
       'VfL Wolfsburg', 'Shakhtar Donetsk', 'Toronto FC',
       'Lokomotiv Moscow', 'Sassuolo', 'New York City FC', 'Fluminense',
       'PSV', 'Levante UD', 'Fulham', 'Watford', 'Atlanta United',
       'Montpellier HSC', 'Galatasaray SK', 'Fenerbahçe SK', 'SD Eibar',
       'Los Angeles FC', 'Sampdoria', 'Al Hilal', 'VfB Stuttgart',
       'SC Braga', 'River Plate', 'Deportivo Alavés',
       'Eintracht Frankfurt', 'Girona FC', 'Guangzhou R&F; FC', 'Burnley',
       'Stoke City', 'Southampton', 'Tianjin Quanjian FC', 'Getafe CF',
       'Beijing Renhe FC', 'Montreal Impact', 'Chievo Verona', 'Genoa',
       'Portland Timbers', 'Tigres U.A.N.L.', 'RCD Espanyol',
       'Hebei China Fortune FC', 'Cagliari', 'Chicago Fire', 'DC United',
       'Sagan Tosu', 'Dynamo Kyiv', 'Santos', 'Internacional',
       'América FC (Minas Gerais)', 'Independiente', 'Boca Juniors',
       'Cruz Azul', '1. FSV Mainz 05', 'Bournemouth', 'Spartak Moscow',
       'Racing Club', 'FC Augsburg', 'Fiorentina', 'FC Nantes',
       'Feyenoord', 'Club Brugge KV', 'Brighton & Hove Albion', 'Al Ahli',
       'Jiangsu Suning FC', 'SC Freiburg', 'PAOK', 'Stade Rennais FC',
       'Trabzonspor', 'SPAL', 'Portimonense SC', 'Olympiacos CFP',
       'Club Atlético Huracán', 'Kasimpaşa SK', 'Newcastle United',
       'Frosinone', 'Querétaro', 'KRC Genk', 'Hannover 96',
       'Stade Malherbe Caen', 'Godoy Cruz', 'Toulouse Football Club',
       'RSC Anderlecht', 'Huddersfield Town', 'CD Tondela',
       'Seattle Sounders FC', 'Hamburger SV', 'FC Red Bull Salzburg',
       'Rio Ave FC', 'FC Girondins de Bordeaux', 'Melbourne Victory',
       'Parma', 'FC Basel 1893', 'Al Wehda', 'BSC Young Boys', 'KAA Gent',
       'Al Ittihad', 'Standard de Liège', 'Shanghai Greenland Shenhua FC',
       'Colo-Colo', 'Junior FC', 'West Bromwich Albion',
       'RC Strasbourg Alsace', 'Göztepe SK', 'Deportivo Cali',
       'Deportivo Toluca', 'Bologna', 'Nagoya Grampus', 'Amiens SC',
       'Changchun Yatai FC', 'Club Atlético Lanús', 'Botafogo',
       'Club América', 'Udinese', 'Real Valladolid CF', 'CD Leganés',
       'Club Atlético Banfield', 'Celtic', 'Vitória Guimarães',
       'FC København', 'UD Las Palmas', 'Deportivo de La Coruña',
       'Universidad Católica', 'San Lorenzo de Almagro', 'Rayo Vallecano',
       'Monterrey', 'Columbus Crew SC', 'MKE Ankaragücü',
       'Guizhou Hengfeng FC', 'Swansea City', 'Tianjin TEDA FC',
       'Chongqing Dangdai Lifan FC SWM Team', 'AEK Athens', 'Al Taawoun',
       'Melbourne City FC', 'En Avant de Guingamp',
       'Akhisar Belediyespor', 'Foggia', 'LOSC Lille', '1. FC Nürnberg',
       'Clube Sport Marítimo', 'Real Sporting de Gijón', 'BB Erzurumspor',
       'Shandong Luneng TaiShan FC', 'Club Atlético Colón', 'Bahia',
       'Once Caldas', 'FC Groningen', 'Angers SCO', 'Paraná',
       'Antalyaspor', 'Minnesota United FC', 'Club León', 'Empoli',
       'VVV-Venlo', 'Leeds United', 'Viktoria Plzeň', 'Alanyaspor',
       'Atlético Paranaense', 'Derby County', 'Kawasaki Frontale',
       'Cardiff City', 'Aston Villa', 'Guadalajara', 'Dijon FCO',
       'Santos Laguna', 'Málaga CF', 'Vitória', 'Çaykur Rizespor',
       'U.N.A.M.', 'Nottingham Forest', 'Royal Antwerp FC',
       'Club Tijuana', 'Sport Club do Recife', 'Real Salt Lake',
       'AZ Alkmaar', 'SK Slavia Praha', 'Willem II', 'Middlesbrough',
       'Dinamo Zagreb', 'Club Atlas', 'Granada CF', 'Sydney FC',
       'Sporting Kansas City', 'SV Zulte-Waregem', 'Philadelphia Union',
       'Real Oviedo', 'Pachuca', 'Boavista FC', 'Atiker Konyaspor',
       'Kaizer Chiefs', 'GD Chaves', 'Palermo', 'Atlético Nacional',
       'Puebla FC', 'Perth Glory', 'Panathinaikos FC', 'FC Sion',
       'Vitória de Setúbal', 'New York Red Bulls', 'Al Shabab',
       'Monarcas Morelia', 'Albacete BP', 'Rangers FC', 'Sparta Praha',
       'Legia Warszawa', 'Urawa Red Diamonds', 'Rosario Central',
       'Stade de Reims', 'ADO Den Haag', 'Chapecoense', 'FC Midtjylland',
       'San Jose Earthquakes', 'Belgrano de Córdoba', 'Brescia',
       'Kashima Antlers', 'CD Everton de Viña del Mar',
       'Fortuna Düsseldorf', 'SD Huesca', 'Preston North End',
       'Club Atlético Talleres', 'Benevento', 'Vitesse',
       'Gimnasia y Esgrima La Plata', 'Houston Dynamo', 'Club Necaxa',
       'Norwich City', 'Holstein Kiel', 'Ettifaq FC', 'Kayserispor',
       '1. FC Heidenheim 1846', 'Brentford', 'Yeni Malatyaspor',
       'Lobos BUAP', 'Bursaspor', 'Ceará Sporting Club',
       'Sheffield United', 'FC Ingolstadt 04', 'Estudiantes de La Plata',
       'AIK', 'Queens Park Rangers', 'Suwon Samsung Bluewings',
       'Heart of Midlothian', 'Reading', 'FC Dallas', 'Heracles Almelo',
       'Venezia FC', 'CD Lugo', 'Henan Jianye FC', 'Orlando City SC',
       'CA Osasuna', 'NAC Breda', 'Livorno', 'Universidad de Chile',
       'Brøndby IF', 'Aberdeen', 'Defensa y Justicia', 'Atlético Tucumán',
       'Blackburn Rovers', 'SV Darmstadt 98', 'Moreirense FC',
       'Sanfrecce Hiroshima', 'CD Numancia', 'KV Oostende', 'FC Utrecht',
       'Vancouver Whitecaps FC', 'Odense Boldklub', 'SC Heerenveen',
       'Racing Club de Lens', 'Independiente Santa Fe',
       'Sporting de Charleroi', 'Millonarios FC', 'Sheffield Wednesday',
       'Perugia', 'Daegu FC', 'Vélez Sarsfield',
       'Grasshopper Club Zürich', 'Sivasspor', 'Nîmes Olympique',
       'Rosenborg BK', 'SK Sturm Graz', 'FC Metz',
       'CD Universidad de Concepción', 'Hellas Verona', 'Brisbane Roar',
       'CD Feirense', 'Hull City', 'Waasland-Beveren', 'Neuchâtel Xamax',
       'Real Zaragoza', 'CD Aves', 'Millwall', 'Unión de Santa Fe',
       'KAS Eupen', 'Cádiz CF', 'FC Tokyo', 'CD Tenerife',
       '1. FC Union Berlin', 'Al Fayha', 'AJ Auxerre',
       'Patriotas Boyacá FC', 'Molde FK', 'Bristol City', 'CD Nacional',
       'Sporting Lokeren', 'FC St. Pauli', 'Deportes Iquique',
       'Al Qadisiyah', 'Atlético Bucaramanga', 'Club Atlético Tigre',
       'FK Austria Wien', 'Patronato', 'Malmö FF', 'Kashiwa Reysol',
       'US Cremonese', 'VfL Bochum 1848', 'SK Rapid Wien',
       'KSV Cercle Brugge', 'Rionegro Águilas', 'Gimnàstic de Tarragona',
       'Lecce', 'Santa Clara', 'BK Häcken', 'New England Revolution',
       'Orlando Pirates', 'Atlético Huila', 'Western Sydney Wanderers',
       'Kalmar FF', 'Independiente Medellín', 'Fortuna Sittard',
       'Lech Poznań', 'Djurgårdens IF', 'CF Reus Deportiu', 'SK Brann',
       'Ulsan Hyundai FC', 'Sint-Truidense VV', 'Carpi', 'Al Fateh',
       'Royal Excel Mouscron', 'AC Ajaccio', 'PEC Zwolle', 'Sunderland',
       'Club Atlético Aldosivi', 'US Salernitana 1919', 'FC Lorient',
       'Argentinos Juniors', 'AD Alcorcón', 'Crotone', 'Excelsior',
       'KV Kortrijk', 'IFK Norrköping', 'Adelaide United',
       'FC St. Gallen', 'Tiburones Rojos de Veracruz', 'CD Palestino',
       'Jeju United FC', 'Deportes Tolima', 'Jeonbuk Hyundai Motors',
       'Birmingham City', 'América de Cali', 'La Equidad', 'Spezia',
       'Aalborg BK', 'Le Havre AC', 'Górnik Zabrze',
       'Central Coast Mariners', 'Wigan Athletic',
       'Jagiellonia Białystok', 'Cittadella', 'Hibernian', 'FC Lugano',
       'San Martín de San Juan', 'Strømsgodset IF', "Newell's Old Boys",
       'Al Faisaly', 'Colorado Rapids', 'IF Elfsborg', 'SV Sandhausen',
       'Al Batin', 'Stade Brestois 29', 'UD Almería', 'Gyeongnam FC',
       'Yokohama F. Marinos', 'Kilmarnock', 'Pescara', 'Newcastle Jets',
       'Córdoba CF', 'RCD Mallorca', 'Hammarby IF', 'Cerezo Osaka',
       'KFC Uerdingen 05', 'Shimizu S-Pulse', 'MSV Duisburg',
       'Os Belenenses', 'DSC Arminia Bielefeld', 'Ipswich Town',
       'FC Seoul', 'Lechia Gdańsk', 'Gamba Osaka', 'CF Rayo Majadahonda',
       'LASK Linz', 'Bolton Wanderers', 'Al Raed', 'Extremadura UD',
       'SC Paderborn 07', 'Wellington Phoenix', 'Unión Española',
       'Alianza Petrolera', 'Cracovia', 'Gangwon FC', 'Júbilo Iwata',
       'Elche CF', 'AS Béziers', 'La Berrichonne de Châteauroux',
       'Clermont Foot 63', 'ESTAC Troyes', '1. FC Magdeburg',
       'Pohang Steelers', 'Örebro SK', 'Arka Gdynia', 'SG Dynamo Dresden',
       'SpVgg Greuther Fürth', 'CD Huachipato', 'Wisła Kraków',
       'Stabæk Fotball', 'Eintracht Braunschweig', 'Valenciennes FC',
       'FC Thun', 'San Luis de Quillota', ' SSV Jahn Regensburg',
       'Cosenza', 'FC Nordsjælland', 'FC Erzgebirge Aue',
       'Jeonnam Dragons', 'Wolfsberger AC',
       'Chamois Niortais Football Club', 'Club Deportes Temuco',
       'AS Nancy Lorraine', 'Red Star FC', 'Al Hazem', 'Pogoń Szczecin',
       'Charlton Athletic', 'Grenoble Foot 38', 'FC Hansa Rostock',
       'San Martin de Tucumán', 'Incheon United FC', 'Śląsk Wrocław',
       'GFC Ajaccio', '1. FC Kaiserslautern', 'Deportivo Pasto',
       'Lincoln City', 'Motherwell', 'Rotherham United', 'Burton Albion',
       'Wisła Płock', 'FC Wacker Innsbruck', 'Peterborough United',
       'Ascoli', 'FC Zürich', 'Fleetwood Town', 'Padova',
       'FC Sochaux-Montbéliard', 'SV Wehen Wiesbaden', 'Unión La Calera',
       'Scunthorpe United', "CD O'Higgins", 'CD Antofagasta',
       'Plymouth Argyle', 'Aarhus GF', 'Lillestrøm SK', 'Karlsruher SC',
       'GIF Sundsvall', 'FC Emmen', 'Barnsley', 'Audax Italiano',
       'V-Varen Nagasaki', 'Paris FC', 'SpVgg Unterhaching', 'Hobro IK',
       'De Graafschap', 'Hokkaido Consadole Sapporo', 'Tromsø IL',
       'FC Luzern', 'FK Haugesund', 'Zagłębie Lubin', 'VfR Aalen',
       'Dundalk', 'Oxford United', 'Piast Gliwice', 'Ohod Club',
       'Östersunds FK', 'Vegalta Sendai', 'Crawley Town',
       'FC Admira Wacker Mödling', 'Vålerenga Fotball', 'Dundee FC',
       'Portsmouth', 'Envigado FC', 'Miedź Legnica', 'Odds BK',
       'SC Fortuna Köln', 'US Orléans Loiret Football', 'Sarpsborg 08 FF',
       'Jaguares de Córdoba', 'Bradford City', 'Accrington Stanley',
       'St. Johnstone FC', 'Boyacá Chicó FC', 'Luton Town',
       'SV Mattersburg', 'Kristiansund BK', 'Sangju Sangmu FC',
       'Rochdale', 'Walsall', 'Korona Kielce', 'Shonan Bellmare',
       'FC Würzburger Kickers', 'FSV Zwickau', 'St. Mirren', 'AC Horsens',
       'Esbjerg fB', 'HJK Helsinki', 'Southend United', 'Bristol Rovers',
       'Hamilton Academical FC', 'TSV 1860 München', 'Curicó Unido',
       'SCR Altach', 'Ranheim Fotball', 'Stevenage',
       'SG Sonnenhof Großaspach', 'Oldham Athletic', 'Milton Keynes Dons',
       'FK Bodø/Glimt', 'SC Preußen Münster', 'Wycombe Wanderers',
       'Vejle Boldklub', 'Bury', 'Randers FC', 'VfL Osnabrück',
       'SønderjyskE', 'IFK Göteborg', 'Mansfield Town', 'Coventry City',
       'Waterford FC', 'Shrewsbury', 'IK Start', 'Gillingham',
       'FC Energie Cottbus', 'FC Carl Zeiss Jena', 'Hallescher FC',
       'SV Meppen', 'AFC Wimbledon', 'Blackpool', 'Doncaster Rovers',
       'Sandefjord Fotball', 'VfL Sportfreunde Lotte', 'Cheltenham Town',
       'IK Sirius', 'Vendsyssel FF', 'Swindon Town', 'Notts County',
       'SKN St. Pölten', 'Exeter City', 'Northampton Town',
       'Shamrock Rovers', 'Colchester United', 'Livingston FC',
       'TSV Hartberg', 'Tranmere Rovers', 'Cambridge United',
       'Grimsby Town', 'Port Vale', 'Itagüí Leones FC',
       'Forest Green Rovers', 'Dalkurd FF', 'Zagłębie Sosnowiec',
       'Carlisle United', 'Trelleborgs FF', "St. Patrick's Athletic",
       'Morecambe', 'Cork City', 'IF Brommapojkarna', 'Crewe Alexandra',
       'Yeovil Town', 'Bohemian FC', 'Macclesfield Town',
       'Newport County', 'Sligo Rovers', 'Derry City', 'Limerick FC',
       'Bray Wanderers'], dtype=object)

In [50]:
f["Club"].nunique()

651

In [51]:
f['Club'].value_counts()

Club
Atlético Madrid            33
CD Leganés                 33
Empoli                     33
RC Celta                   33
Wolverhampton Wanderers    33
                           ..
Chapecoense                20
Tromsø IL                  20
Sligo Rovers               19
Limerick FC                19
Derry City                 18
Name: count, Length: 651, dtype: int64

In [52]:
s=f.select_dtypes(include="object").columns

for i in s[1::]:
    print(i)
    print(f[i].unique())
    print(f[i].nunique())
    print(f[i].value_counts())
    print("*"*50)

Nationality
['Argentina' 'Portugal' 'Brazil' 'Spain' 'Belgium' 'Croatia' 'Uruguay'
 'Slovenia' 'Poland' 'Germany' 'France' 'England' 'Italy' 'Egypt'
 'Colombia' 'Denmark' 'Gabon' 'Wales' 'Senegal' 'Costa Rica' 'Slovakia'
 'Netherlands' 'Bosnia Herzegovina' 'Morocco' 'Serbia' 'Algeria' 'Austria'
 'Greece' 'Chile' 'Sweden' 'Korea Republic' 'Finland' 'Guinea'
 'Montenegro' 'Armenia' 'Switzerland' 'Norway' 'Czech Republic' 'Scotland'
 'Ghana' 'Central African Rep.' 'DR Congo' 'Ivory Coast' 'Russia'
 'Ukraine' 'Iceland' 'Mexico' 'Jamaica' 'Albania' 'Venezuela' 'Japan'
 'Turkey' 'Ecuador' 'Paraguay' 'Mali' 'Nigeria' 'Cameroon'
 'Dominican Republic' 'Israel' 'Kenya' 'Hungary' 'Republic of Ireland'
 'Romania' 'United States' 'Cape Verde' 'Australia' 'Peru' 'Togo' 'Syria'
 'Zimbabwe' 'Angola' 'Burkina Faso' 'Iran' 'Estonia' 'Tunisia'
 'Equatorial Guinea' 'New Zealand' 'FYR Macedonia' 'United Arab Emirates'
 'China PR' 'Guinea Bissau' 'Bulgaria' 'Kosovo' 'South Africa'
 'Madagascar' 'Georgia' 'Tanzania' 'Gambia' 'Cuba' 'Belarus' 'Uzbekistan'
 'Benin' 'Congo' 'Mozambique' 'Honduras' 'Canada' 'Northern Ireland'
 'Cyprus' 'Saudi Arabia' 'Curacao' 'Moldova' 'Bolivia' 'Trinidad & Tobago'
 'Sierra Leone' 'Zambia' 'Chad' 'Philippines' 'Haiti' 'Comoros' 'Libya'
 'Panama' 'São Tomé & Príncipe' 'Eritrea' 'Oman' 'Iraq' 'Burundi' 'Fiji'
 'New Caledonia' 'Lithuania' 'Luxembourg' 'Korea DPR' 'Liechtenstein'
 'St Kitts Nevis' 'Latvia' 'Suriname' 'Uganda' 'El Salvador' 'Bermuda'
 'Kuwait' 'Antigua & Barbuda' 'Thailand' 'Mauritius' 'Guatemala' 'Liberia'
 'Kazakhstan' 'Niger' 'Mauritania' 'Montserrat' 'Namibia' 'Azerbaijan'
 'Guam' 'Faroe Islands' 'Nicaragua' 'Barbados' 'Lebanon' 'Palestine'
 'Guyana' 'Sudan' 'St Lucia' 'Ethiopia' 'Puerto Rico' 'Grenada' 'Jordan'
 'Rwanda' 'Qatar' 'Afghanistan' 'Hong Kong' 'Andorra' 'Malta' 'Belize'
 'South Sudan' 'Indonesia' 'Botswana']
163
Nationality
England        1655
Germany        1195
Spain          1071
Argentina       935
France          910
               ...
Malta             1
Belize            1
South Sudan       1
Indonesia         1
Botswana          1
Name: count, Length: 163, dtype: int64
**************************************************
Club
['FC Barcelona' 'Juventus' 'Paris Saint-Germain' 'Manchester United'
 'Manchester City' 'Chelsea' 'Real Madrid' 'Atlético Madrid'
 'FC Bayern München' 'Tottenham Hotspur' 'Liverpool' 'Napoli' 'Arsenal'
 'Milan' 'Inter' 'Lazio' 'Borussia Dortmund' 'Vissel Kobe'
 'Olympique Lyonnais' 'Roma' 'Valencia CF'
 'Guangzhou Evergrande Taobao FC' 'FC Porto' 'FC Schalke 04' 'Beşiktaş JK'
 'LA Galaxy' 'Sporting CP' 'Real Betis' 'Olympique de Marseille'
 'RC Celta' 'Bayer 04 Leverkusen' 'Real Sociedad' 'Villarreal CF'
 'Sevilla FC' 'SL Benfica' 'AS Saint-Étienne' 'AS Monaco' 'Leicester City'
 'Atalanta' 'Grêmio' 'Atlético Mineiro' 'RB Leipzig' 'Ajax'
 'Dalian YiFang FC' 'Everton' 'West Ham United' '1. FC Köln'
 'TSG 1899 Hoffenheim' 'Shanghai SIPG FC' 'OGC Nice' 'Al Nassr'
 'Wolverhampton Wanderers' 'Borussia Mönchengladbach' 'Hertha BSC'
 'SV Werder Bremen' 'Cruzeiro' 'Athletic Club de Bilbao' 'Torino'
 'Medipol Başakşehir FK' 'Beijing Sinobo Guoan FC' 'Crystal Palace'
 'PFC CSKA Moscow' 'VfL Wolfsburg' 'Shakhtar Donetsk' 'Toronto FC'
 'Lokomotiv Moscow' 'Sassuolo' 'New York City FC' 'Fluminense' 'PSV'
 'Levante UD' 'Fulham' 'Watford' 'Atlanta United' 'Montpellier HSC'
 'Galatasaray SK' 'Fenerbahçe SK' 'SD Eibar' 'Los Angeles FC' 'Sampdoria'
 'Al Hilal' 'VfB Stuttgart' 'SC Braga' 'River Plate' 'Deportivo Alavés'
 'Eintracht Frankfurt' 'Girona FC' 'Guangzhou R&F; FC' 'Burnley'
 'Stoke City' 'Southampton' 'Tianjin Quanjian FC' 'Getafe CF'
 'Beijing Renhe FC' 'Montreal Impact' 'Chievo Verona' 'Genoa'
 'Portland Timbers' 'Tigres U.A.N.L.' 'RCD Espanyol'
 'Hebei China Fortune FC' 'Cagliari' 'Chicago Fire' 'DC United'
 'Sagan Tosu' 'Dynamo Kyiv' 'Santos' 'Internacional'
 'América FC (Minas Gerais)' 'Independiente' 'Boca Juniors' 'Cruz Azul'
 '1. FSV Mainz 05' 'Bournemouth' 'Spartak Moscow' 'Racing Club'
 'FC Augsburg' 'Fiorentina' 'FC Nantes' 'Feyenoord' 'Club Brugge KV'
 'Brighton & Hove Albion' 'Al Ahli' 'Jiangsu Suning FC' 'SC Freiburg'
 'PAOK' 'Stade Rennais FC' 'Trabzonspor' 'SPAL' 'Portimonense SC'
 'Olympiacos CFP' 'Club Atlético Huracán' 'Kasimpaşa SK'
 'Newcastle United' 'Frosinone' 'Querétaro' 'KRC Genk' 'Hannover 96'
 'Stade Malherbe Caen' 'Godoy Cruz' 'Toulouse Football Club'
 'RSC Anderlecht' 'Huddersfield Town' 'CD Tondela' 'Seattle Sounders FC'
 'Hamburger SV' 'FC Red Bull Salzburg' 'Rio Ave FC'
 'FC Girondins de Bordeaux' 'Melbourne Victory' 'Parma' 'FC Basel 1893'
 'Al Wehda' 'BSC Young Boys' 'KAA Gent' 'Al Ittihad' 'Standard de Liège'
 'Shanghai Greenland Shenhua FC' 'Colo-Colo' 'Junior FC'
 'West Bromwich Albion' 'RC Strasbourg Alsace' 'Göztepe SK'
 'Deportivo Cali' 'Deportivo Toluca' 'Bologna' 'Nagoya Grampus'
 'Amiens SC' 'Changchun Yatai FC' 'Club Atlético Lanús' 'Botafogo'
 'Club América' 'Udinese' 'Real Valladolid CF' 'CD Leganés'
 'Club Atlético Banfield' 'Celtic' 'Vitória Guimarães' 'FC København'
 'UD Las Palmas' 'Deportivo de La Coruña' 'Universidad Católica'
 'San Lorenzo de Almagro' 'Rayo Vallecano' 'Monterrey' 'Columbus Crew SC'
 'MKE Ankaragücü' 'Guizhou Hengfeng FC' 'Swansea City' 'Tianjin TEDA FC'
 'Chongqing Dangdai Lifan FC SWM Team' 'AEK Athens' 'Al Taawoun'
 'Melbourne City FC' 'En Avant de Guingamp' 'Akhisar Belediyespor'
 'Foggia' 'LOSC Lille' '1. FC Nürnberg' 'Clube Sport Marítimo'
 'Real Sporting de Gijón' 'BB Erzurumspor' 'Shandong Luneng TaiShan FC'
 'Club Atlético Colón' 'Bahia' 'Once Caldas' 'FC Groningen' 'Angers SCO'
 'Paraná' 'Antalyaspor' 'Minnesota United FC' 'Club León' 'Empoli'
 'VVV-Venlo' 'Leeds United' 'Viktoria Plzeň' 'Alanyaspor'
 'Atlético Paranaense' 'Derby County' 'Kawasaki Frontale' 'Cardiff City'
 'Aston Villa' 'Guadalajara' 'Dijon FCO' 'Santos Laguna' 'Málaga CF'
 'Vitória' 'Çaykur Rizespor' 'U.N.A.M.' 'Nottingham Forest'
 'Royal Antwerp FC' 'Club Tijuana' 'Sport Club do Recife' 'Real Salt Lake'
 'AZ Alkmaar' 'SK Slavia Praha' 'Willem II' 'Middlesbrough'
 'Dinamo Zagreb' 'Club Atlas' 'Granada CF' 'Sydney FC'
 'Sporting Kansas City' 'SV Zulte-Waregem' 'Philadelphia Union'
 'Real Oviedo' 'Pachuca' 'Boavista FC' 'Atiker Konyaspor' 'Kaizer Chiefs'
 'GD Chaves' 'Palermo' 'Atlético Nacional' 'Puebla FC' 'Perth Glory'
 'Panathinaikos FC' 'FC Sion' 'Vitória de Setúbal' 'New York Red Bulls'
 'Al Shabab' 'Monarcas Morelia' 'Albacete BP' 'Rangers FC' 'Sparta Praha'
 'Legia Warszawa' 'Urawa Red Diamonds' 'Rosario Central' 'Stade de Reims'
 'ADO Den Haag' 'Chapecoense' 'FC Midtjylland' 'San Jose Earthquakes'
 'Belgrano de Córdoba' 'Brescia' 'Kashima Antlers'
 'CD Everton de Viña del Mar' 'Fortuna Düsseldorf' 'SD Huesca'
 'Preston North End' 'Club Atlético Talleres' 'Benevento' 'Vitesse'
 'Gimnasia y Esgrima La Plata' 'Houston Dynamo' 'Club Necaxa'
 'Norwich City' 'Holstein Kiel' 'Ettifaq FC' 'Kayserispor'
 '1. FC Heidenheim 1846' 'Brentford' 'Yeni Malatyaspor' 'Lobos BUAP'
 'Bursaspor' 'Ceará Sporting Club' 'Sheffield United' 'FC Ingolstadt 04'
 'Estudiantes de La Plata' 'AIK' 'Queens Park Rangers'
 'Suwon Samsung Bluewings' 'Heart of Midlothian' 'Reading' 'FC Dallas'
 'Heracles Almelo' 'Venezia FC' 'CD Lugo' 'Henan Jianye FC'
 'Orlando City SC' 'CA Osasuna' 'NAC Breda' 'Livorno'
 'Universidad de Chile' 'Brøndby IF' 'Aberdeen' 'Defensa y Justicia'
 'Atlético Tucumán' 'Blackburn Rovers' 'SV Darmstadt 98' 'Moreirense FC'
 'Sanfrecce Hiroshima' 'CD Numancia' 'KV Oostende' 'FC Utrecht'
 'Vancouver Whitecaps FC' 'Odense Boldklub' 'SC Heerenveen'
 'Racing Club de Lens' 'Independiente Santa Fe' 'Sporting de Charleroi'
 'Millonarios FC' 'Sheffield Wednesday' 'Perugia' 'Daegu FC'
 'Vélez Sarsfield' 'Grasshopper Club Zürich' 'Sivasspor' 'Nîmes Olympique'
 'Rosenborg BK' 'SK Sturm Graz' 'FC Metz' 'CD Universidad de Concepción'
 'Hellas Verona' 'Brisbane Roar' 'CD Feirense' 'Hull City'
 'Waasland-Beveren' 'Neuchâtel Xamax' 'Real Zaragoza' 'CD Aves' 'Millwall'
 'Unión de Santa Fe' 'KAS Eupen' 'Cádiz CF' 'FC Tokyo' 'CD Tenerife'
 '1. FC Union Berlin' 'Al Fayha' 'AJ Auxerre' 'Patriotas Boyacá FC'
 'Molde FK' 'Bristol City' 'CD Nacional' 'Sporting Lokeren' 'FC St. Pauli'
 'Deportes Iquique' 'Al Qadisiyah' 'Atlético Bucaramanga'
 'Club Atlético Tigre' 'FK Austria Wien' 'Patronato' 'Malmö FF'
 'Kashiwa Reysol' 'US Cremonese' 'VfL Bochum 1848' 'SK Rapid Wien'
 'KSV Cercle Brugge' 'Rionegro Águilas' 'Gimnàstic de Tarragona' 'Lecce'
 'Santa Clara' 'BK Häcken' 'New England Revolution' 'Orlando Pirates'
 'Atlético Huila' 'Western Sydney Wanderers' 'Kalmar FF'
 'Independiente Medellín' 'Fortuna Sittard' 'Lech Poznań' 'Djurgårdens IF'
 'CF Reus Deportiu' 'SK Brann' 'Ulsan Hyundai FC' 'Sint-Truidense VV'
 'Carpi' 'Al Fateh' 'Royal Excel Mouscron' 'AC Ajaccio' 'PEC Zwolle'
 'Sunderland' 'Club Atlético Aldosivi' 'US Salernitana 1919' 'FC Lorient'
 'Argentinos Juniors' 'AD Alcorcón' 'Crotone' 'Excelsior' 'KV Kortrijk'
 'IFK Norrköping' 'Adelaide United' 'FC St. Gallen'
 'Tiburones Rojos de Veracruz' 'CD Palestino' 'Jeju United FC'
 'Deportes Tolima' 'Jeonbuk Hyundai Motors' 'Birmingham City'
 'América de Cali' 'La Equidad' 'Spezia' 'Aalborg BK' 'Le Havre AC'
 'Górnik Zabrze' 'Central Coast Mariners' 'Wigan Athletic'
 'Jagiellonia Białystok' 'Cittadella' 'Hibernian' 'FC Lugano'
 'San Martín de San Juan' 'Strømsgodset IF' "Newell's Old Boys"
 'Al Faisaly' 'Colorado Rapids' 'IF Elfsborg' 'SV Sandhausen' 'Al Batin'
 'Stade Brestois 29' 'UD Almería' 'Gyeongnam FC' 'Yokohama F. Marinos'
 'Kilmarnock' 'Pescara' 'Newcastle Jets' 'Córdoba CF' 'RCD Mallorca'
 'Hammarby IF' 'Cerezo Osaka' 'KFC Uerdingen 05' 'Shimizu S-Pulse'
 'MSV Duisburg' 'Os Belenenses' 'DSC Arminia Bielefeld' 'Ipswich Town'
 'FC Seoul' 'Lechia Gdańsk' 'Gamba Osaka' 'CF Rayo Majadahonda'
 'LASK Linz' 'Bolton Wanderers' 'Al Raed' 'Extremadura UD'
 'SC Paderborn 07' 'Wellington Phoenix' 'Unión Española'
 'Alianza Petrolera' 'Cracovia' 'Gangwon FC' 'Júbilo Iwata' 'Elche CF'
 'AS Béziers' 'La Berrichonne de Châteauroux' 'Clermont Foot 63'
 'ESTAC Troyes' '1. FC Magdeburg' 'Pohang Steelers' 'Örebro SK'
 'Arka Gdynia' 'SG Dynamo Dresden' 'SpVgg Greuther Fürth' 'CD Huachipato'
 'Wisła Kraków' 'Stabæk Fotball' 'Eintracht Braunschweig'
 'Valenciennes FC' 'FC Thun' 'San Luis de Quillota' ' SSV Jahn Regensburg'
 'Cosenza' 'FC Nordsjælland' 'FC Erzgebirge Aue' 'Jeonnam Dragons'
 'Wolfsberger AC' 'Chamois Niortais Football Club' 'Club Deportes Temuco'
 'AS Nancy Lorraine' 'Red Star FC' 'Al Hazem' 'Pogoń Szczecin'
 'Charlton Athletic' 'Grenoble Foot 38' 'FC Hansa Rostock'
 'San Martin de Tucumán' 'Incheon United FC' 'Śląsk Wrocław' 'GFC Ajaccio'
 '1. FC Kaiserslautern' 'Deportivo Pasto' 'Lincoln City' 'Motherwell'
 'Rotherham United' 'Burton Albion' 'Wisła Płock' 'FC Wacker Innsbruck'
 'Peterborough United' 'Ascoli' 'FC Zürich' 'Fleetwood Town' 'Padova'
 'FC Sochaux-Montbéliard' 'SV Wehen Wiesbaden' 'Unión La Calera'
 'Scunthorpe United' "CD O'Higgins" 'CD Antofagasta' 'Plymouth Argyle'
 'Aarhus GF' 'Lillestrøm SK' 'Karlsruher SC' 'GIF Sundsvall' 'FC Emmen'
 'Barnsley' 'Audax Italiano' 'V-Varen Nagasaki' 'Paris FC'
 'SpVgg Unterhaching' 'Hobro IK' 'De Graafschap'
 'Hokkaido Consadole Sapporo' 'Tromsø IL' 'FC Luzern' 'FK Haugesund'
 'Zagłębie Lubin' 'VfR Aalen' 'Dundalk' 'Oxford United' 'Piast Gliwice'
 'Ohod Club' 'Östersunds FK' 'Vegalta Sendai' 'Crawley Town'
 'FC Admira Wacker Mödling' 'Vålerenga Fotball' 'Dundee FC' 'Portsmouth'
 'Envigado FC' 'Miedź Legnica' 'Odds BK' 'SC Fortuna Köln'
 'US Orléans Loiret Football' 'Sarpsborg 08 FF' 'Jaguares de Córdoba'
 'Bradford City' 'Accrington Stanley' 'St. Johnstone FC' 'Boyacá Chicó FC'
 'Luton Town' 'SV Mattersburg' 'Kristiansund BK' 'Sangju Sangmu FC'
 'Rochdale' 'Walsall' 'Korona Kielce' 'Shonan Bellmare'
 'FC Würzburger Kickers' 'FSV Zwickau' 'St. Mirren' 'AC Horsens'
 'Esbjerg fB' 'HJK Helsinki' 'Southend United' 'Bristol Rovers'
 'Hamilton Academical FC' 'TSV 1860 München' 'Curicó Unido' 'SCR Altach'
 'Ranheim Fotball' 'Stevenage' 'SG Sonnenhof Großaspach' 'Oldham Athletic'
 'Milton Keynes Dons' 'FK Bodø/Glimt' 'SC Preußen Münster'
 'Wycombe Wanderers' 'Vejle Boldklub' 'Bury' 'Randers FC' 'VfL Osnabrück'
 'SønderjyskE' 'IFK Göteborg' 'Mansfield Town' 'Coventry City'
 'Waterford FC' 'Shrewsbury' 'IK Start' 'Gillingham' 'FC Energie Cottbus'
 'FC Carl Zeiss Jena' 'Hallescher FC' 'SV Meppen' 'AFC Wimbledon'
 'Blackpool' 'Doncaster Rovers' 'Sandefjord Fotball'
 'VfL Sportfreunde Lotte' 'Cheltenham Town' 'IK Sirius' 'Vendsyssel FF'
 'Swindon Town' 'Notts County' 'SKN St. Pölten' 'Exeter City'
 'Northampton Town' 'Shamrock Rovers' 'Colchester United' 'Livingston FC'
 'TSV Hartberg' 'Tranmere Rovers' 'Cambridge United' 'Grimsby Town'
 'Port Vale' 'Itagüí Leones FC' 'Forest Green Rovers' 'Dalkurd FF'
 'Zagłębie Sosnowiec' 'Carlisle United' 'Trelleborgs FF'
 "St. Patrick's Athletic" 'Morecambe' 'Cork City' 'IF Brommapojkarna'
 'Crewe Alexandra' 'Yeovil Town' 'Bohemian FC' 'Macclesfield Town'
 'Newport County' 'Sligo Rovers' 'Derry City' 'Limerick FC'
 'Bray Wanderers']
651
Club
Atlético Madrid            33
CD Leganés                 33
Empoli                     33
RC Celta                   33
Wolverhampton Wanderers    33
                           ..
Chapecoense                20
Tromsø IL                  20
Sligo Rovers               19
Limerick FC                19
Derry City                 18
Name: count, Length: 651, dtype: int64
**************************************************
P_Foot
['Left' 'Right']
2
P_Foot
Right    13748
Left      4159
Name: count, dtype: int64
**************************************************
Position
['RF' 'ST' 'LW' 'GK' 'RCM' 'LF' 'RS' 'RCB' 'LCM' 'CB' 'LDM' 'CAM' 'CDM'
 'LS' 'LCB' 'RM' 'LAM' 'LM' 'LB' 'RDM' 'RW' 'CM' 'RB' 'RAM' 'CF' 'RWB'
 'LWB']
27
Position
ST     2130
GK     1989
CB     1751
CM     1377
LB     1304
RB     1268
RM     1114
LM     1086
CAM     946
CDM     936
RCB     652
LCB     635
LCM     389
RCM     387
LW      374
RW      365
RDM     246
LDM     239
LS      206
RS      201
RWB      87
LWB      78
CF       74
LAM      21
RAM      21
RF       16
LF       15
Name: count, dtype: int64
**************************************************
Contract_Valid_Until
['2021-01-01' '2022-01-01' '2020-01-01' '2023-01-01' '2019-01-01'
 '2024-01-01' '2019-06-30' '2025-01-01' '2026-01-01' '2018-12-31'
 '2018-01-01' '2020-05-31' '2020-06-30' '2019-05-31' '2019-12-31'
 '2019-06-01' '2019-01-04' '2019-01-31' '2019-01-07' '2019-01-02'
 '2019-01-06' '2019-10-14' '2019-01-03' '2019-05-04' '2019-01-12'
 '2019-01-25' '2019-01-18' '2019-12-01' '2018-11-30' '2020-02-27'
 '2019-01-05' '2019-01-15' '2019-01-30' '2019-01-11' '2019-01-20']
35
Contract_Valid_Until
2019-01-01    4865
2021-01-01    4358
2020-01-01    4027
2022-01-01    1475
2023-01-01    1051
2019-06-30     931
2018-01-01     886
2018-12-31     144
2019-05-31      60
2024-01-01      23
2020-06-30      14
2019-01-31      13
2025-01-01       7
2019-01-05       6
2019-01-02       6
2019-10-14       5
2019-01-12       5
2019-01-06       4
2019-01-07       3
2019-12-31       3
2019-01-25       3
2020-05-31       2
2026-01-01       2
2019-12-01       2
2018-11-30       2
2019-06-01       1
2019-01-04       1
2019-01-18       1
2019-05-04       1
2019-01-03       1
2020-02-27       1
2019-01-15       1
2019-01-30       1
2019-01-11       1
2019-01-20       1
Name: count, dtype: int64
**************************************************

In [53]:
f.query("Club=='Real Madrid' and Age > 30")

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
46,193041,K. Navas,31,Costa Rica,87,87,Real Madrid,30500.0,195.0,Right,3.0,1.0,GK,2014,2020-01-01,6.083333,176.0,62500.0
697,177644,Kiko Casilla,31,Spain,79,79,Real Madrid,7500.0,105.0,Right,2.0,1.0,GK,2015,2020-01-01,6.250000,190.0,15400.0

In [54]:
f

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [55]:
f.query("Nationality == 'Argentina'").head(11)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,P_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.000000
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.000000
23,153079,S. Agüero,30,Argentina,89,89,Manchester City,64500.0,300.0,Right,4.0,4.0,ST,2011,2021-01-01,5.666667,154.0,119300.000000
38,167664,G. Higuaín,30,Argentina,88,88,Milan,57000.0,245.0,Right,4.0,3.0,LS,2016,2019-06-30,6.083333,196.0,4585.060806
43,201399,M. Icardi,25,Argentina,87,90,Inter,64500.0,130.0,Right,3.0,3.0,ST,2013,2021-01-01,5.916667,165.0,114500.000000
89,192366,N. Otamendi,30,Argentina,85,85,Manchester City,28500.0,170.0,Right,3.0,2.0,CB,2015,2022-01-01,6.000000,179.0,52700.000000
138,183898,A. Di María,30,Argentina,84,84,Paris Saint-Germain,29500.0,125.0,Left,4.0,5.0,RM,2015,2021-01-01,5.916667,152.0,54600.000000
142,178562,E. Banega,30,Argentina,84,84,Sevilla FC,29000.0,31.0,Right,3.0,4.0,CDM,2017,2020-01-01,5.750000,157.0,60900.000000
151,143076,A. Gómez,30,Argentina,84,84,Atalanta,30000.0,53.0,Right,3.0,4.0,LS,2014,2022-01-01,5.416667,150.0,51000.000000
255,207471,F. Vázquez,29,Argentina,82,82,Sevilla FC,21500.0,27.0,Left,2.0,4.0,LCM,2016,2021-01-01,6.083333,181.0,45200.000000
282,191180,J. Pastore,29,Argentina,82,82,Roma,21500.0,84.0,Right,3.0,4.0,CAM,2018,2022-01-01,6.166667,172.0,36600.000000

In [ ]:
pos = f['Position'].unique()
mp={}
for i in pos:
    f.query("Postion == i")["Overall"].max()

array(['RF', 'ST', 'LW', 'GK', 'RCM', 'LF', 'RS', 'RCB', 'LCM', 'CB',
       'LDM', 'CAM', 'CDM', 'LS', 'LCB', 'RM', 'LAM', 'LM', 'LB', 'RDM',
       'RW', 'CM', 'RB', 'RAM', 'CF', 'RWB', 'LWB'], dtype=object)

In [ ]:
f.query("Height > 5.5")